#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool
baseCommand: [nanopolish, vcf2fasta]
label: Merges vcf files generated by multiple nanopore threads running on the same draft genome and returns the polished draft genome.

hints:
  DockerRequirement:
    dockerPull: ttubb/nanopolish:0.11.2
  SoftwareRequirement:
    packages:
      nanopolish:
        specs: [ https://identifiers.org/rrid/RRID:SCR_016157 ]
        version: [ "0.11.2" ]
        
requirements:
  InlineJavascriptRequirement: {}
  InitialWorkDirRequirement:
    listing: [ $(inputs.draft_genome) ]
    
inputs:
  draft_genome:
    label: Draft genome created by assembler.
    type: File
    inputBinding:
      position: 1
      prefix: -g
  vcalls:
    label: Variant call files produced by nanopolish.
    type: File[]
    inputBinding:
      position: 2

outputs:
  polished_genome:
    label: Draft genome after polishing.
    type: stdout

stdout: $(inputs.draft_genome.nameroot+"_polished.fasta")

s:author:
  - class: s:Person
    s:email: mailto:tom.tubb@googlemail.com
    s:name: Tom Tubbesing
s:dateCreated: "2019-02-11"
s:license: "https://spdx.org/licenses/GPL-3.0-or-later.html"

$namespaces:
  s: http://schema.org/
  edam: http://edamontology.org/

$schemas:
  - http://schema.org/docs/schema_org_rdfa.html
  - http://edamontology.org/EDAM_1.18.owl
