#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool
baseCommand: [necat.pl, bridge]
label: Executes necats correct, assemble and bridge modules to create an assembly.
doc: |
  Uses the various modules of the Necat assemblyer (correct, assemble, bridge) to create a de novo assembly from long reads. Most input paramters have to be provided using a Necat-specific config file.

hints:
  SoftwareRequirement:
    packages:
      necat:
        specs: [ "https://github.com/xiaochuanle/NECAT" ]
        version: [ "0.01" ]
        
requirements:
  DockerRequirement:
    dockerImageId: ttubb/necat:release-0.2.0
  InitialWorkDirRequirement:
    listing:
      - $(inputs.reads_list)
      - $(inputs.reads)

inputs:
  necat_config:
    label: Config file generated by necat's config command with all fields filled in.
    type: File
    inputBinding:
      position: 1
  reads_list:
    label: Text file with name of inputs.reads (the file with the nanopore reads).
    type: File
  reads:
    label: File with basecalled ONT nanopore reads.
    type: File

outputs:
  contigs:
    label: Contigs generated in last step (bridging) of necat pipeline.
    type: File
    outputBinding:
      glob: "**/6-bridge_contigs/bridged_contigs.fasta"

s:author:
  - class: s:Person
    s:email: mailto:tom.tubb@googlemail.com
    s:name: Tom Tubbesing
s:dateCreated: "2019-04-11"
s:license: "https://spdx.org/licenses/GPL-3.0-or-later.html"

$namespaces:
  s: "http://schema.org/"
  edam: "http://edamontology.org/"
  cwltool: "http://commonwl.org/cwltool#"

$schemas:
  - http://schema.org/docs/schema_org_rdfa.html
  - http://edamontology.org/EDAM_1.18.owl
