#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow
label: Filters 1D-squared reads from a file of 1D reads.
doc: |
  Takes reads basecalled by guppy_basecaller and guppy_basecaller_1d2 and removes all reads which were used to generate 1d2-reads from the file of 1D-reads. Scripts from https://github.com/gringer/bioinfscripts are downloaded by the docker container and used for this task.

hints:
  SoftwareRequirement:
    #Requires script: https://raw.githubusercontent.com/gringer/bioinfscripts/master/fastx-length.pl
    #Requires script: https://raw.githubusercontent.com/gringer/bioinfscripts/master/fastx-fetch.pl
    packages:
      perl:
        specs: [ https://perldoc.perl.org/5.28.1/perl.html ]
        version: [ "5.28.1" ]

inputs:
  reads_1d:
    label: Reads generated by guppy_basecaller.
    type: File
  reads_1d2:
    label: Reads generated by guppy_basecaller_1d2.
    type: File

outputs:
  reads_1d_filtered:
    label: reads_1d minus all reads present in reads_1d2.
    type: File
    outputSource: filter_1d_reads/reads_1d_filtered

steps:
  create_1d2readname_list:
    label: Extract read IDs from fastq file.
    run: list1d2ReadsTool.cwl
    in:
      reads_1d2: reads_1d2
    out: [reads_1d2_list]
  isolate_ids:
    label: Remove superflous fields from read list.
    run: awkPickSecondFieldTool.cwl
    in:
      inp_record: create_1d2readname_list/reads_1d2_list
    out: [outp_record]
  filter_1d_reads:
    label: Remove all 1d2 reads from the file of 1d reads.
    run: filter1dReadsTool.cwl
    in:
      reads_1d: reads_1d
      readnames_1d2: isolate_ids/outp_record
    out: [reads_1d_filtered]

s:author:
  - class: s:Person
    s:email: mailto:tom.tubb@googlemail.com
    s:name: Tom Tubbesing
s:dateCreated: "2019-04-16"
s:license: "https://spdx.org/licenses/GPL-3.0-or-later.html"

$namespaces:
  s: http://schema.org/
  edam: http://edamontology.org/

$schemas:
  - https://schema.org/version/latest/schema.rdf
  - http://edamontology.org/EDAM_1.18.owl
