#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool
baseCommand: bowtie2

hints:
  DockerRequirement:
    dockerPull: ttubb/bowtie2:release-0.2.0
  SoftwareRequirement:
    packages:
      bowtie2:
        specs: [ "https://github.com/BenLangmead/bowtie2" ]
        version: [ "2.3.5.1" ]
    
requirements:
  InlineJavascriptRequirement: {}
  InitialWorkDirRequirement:
    listing: $(inputs.index_files)

arguments:
  - valueFrom: $(inputs.index_files[0].nameroot.split(".",1)) #prefix of index files
    prefix: -x
  - valueFrom: "--time" #print time spent while mapping

inputs:
  worker_threads:
    label: CPU threads used by bowtie2.
    type: int?
    inputBinding:
      prefix: --threads
  index_files:
    label: Array of index files created by bowtie2-build.
    type: File[]
  reads_fwd:
    label: File with forward paired-end reads (may be zipped as .gz or .bz2).
    type: File?
    inputBinding:
      prefix: "-1"
  reads_rev:
    label: File with reverse paired-end reads (may be zipped as .gz or .bz2).
    type: File
    inputBinding:
      prefix: "-2"
  reads_unpaired:
    label: File with unpaired reads (may be zipped as .gz or .bz2).
    type: File?
    inputBinding:
      prefix: -U

outputs:
  alignment_map:
    label: Map generated by aligning all input reads to the index.
    type: stdout

stdout: "bowtie2_map.sam"

s:author:
  - class: s:Person
    s:email: mailto:tom.tubb@googlemail.com
    s:name: Tom Tubbesing
s:dateCreated: "2019-02-08"
s:license: "https://spdx.org/licenses/GPL-3.0-or-later.html"

$namespaces:
  s: http://schema.org/
  edam: http://edamontology.org/

$schemas:
  - http://schema.org/docs/schema_org_rdfa.html
  - http://edamontology.org/EDAM_1.20.owl
