#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow
label: Uses various quality control tool to control the quality of the input reads.

requirements:
  InlineJavascriptRequirement: {}
  StepInputExpressionRequirement: {}
  MultipleInputFeatureRequirement: {}
  
hints:
  SoftwareRequirement:
    packages:
      fastqc:
        specs: [ https://identifiers.org/RRID:SCR_014583 ]
        version: [ "0.11.5" ]
      nanoqc:
        specs: [ https://github.com/wdecoster/nanoQC ]
        version: [ "0.9.0" ]
      nanoplot:
        specs: [ https://github.com/wdecoster/NanoPlot ]
        version: [ "1.22.0" ]

inputs:
  reads:
    label: Basecalled reads generated by any sequencing method.
    type: File
  worker_threads:
    label: Number of CPU-threads used in computationally intensive steps.
    type: int
    default: 1

outputs:
  read_qc_directory:
    label: Directory containing read qc information from various tools.
    type: Directory
    outputSource: pooling_reports/pool_directory

steps:
  fastqc:
    label: Perform fastqc analysis of reads.
    run: fastqcTool.cwl
    in:
      reads: reads
      worker_threads: worker_threads
    out: [report_directory, report_html, report_zip]
  nanoplot:
    label: Perform nanoplot analysis of reads.
    run: nanoplotTool.cwl
    in:
      reads: reads
      worker_threads: worker_threads
    out: [report_directory]
  nanoqc:
    label: perform nanoqc analysis of reads.
    run: nanoqcTool.cwl
    in:
      reads: reads
    out: [report_directory, logfile, report_html]
  pooling_reports:
    label: Save all tool output into a single read qc directory.
    run: ../misc/poolingTool.cwl
    in:
      namesource: reads
      directory_array: [fastqc/report_directory, nanoplot/report_directory, nanoqc/report_directory]
      newname:
        valueFrom: $("read-qc-reports-for-"+(inputs.namesource.nameroot))
    out: [pool_directory]


s:author:
  - class: s:Person
    s:email: mailto:tom.tubb@googlemail.com
    s:name: Tom Tubbesing
s:dateCreated: "2019-06-27"
s:license: "https://spdx.org/licenses/GPL-3.0-or-later.html"

$namespaces:
  s: http://schema.org/
  edam: http://edamontology.org/

$schemas:
  - http://schema.org/docs/schema_org_rdfa.html
  - http://edamontology.org/EDAM_1.18.owl
