#!/bin/bash

#This script is designed to complete a config file generated by necat's ( https://github.com/xiaochuanle/NECAT ) config command.
#It will write a new config file  and add the parameters which were given to this script via command line arguments.

#Constants
USAGE="USAGE: necat_paramcfg.sh -n PROJECT_NAME -r ONT_READ_LIST -s GENOME_SIZE -t THREADS -c NAME_OF_CONFIG_FILE"
CONFIG_FILENAME_PREFIX="filled_"

#Read in command line arguments.
NUMBER_OF_ARGUMENTS=0
while getopts :n:r:s:t:c: options; do
      case $options in
	  n) PROJECT_NAME=${OPTARG};((NUMBER_OF_ARGUMENTS++));;
	  r) ONT_READ_LIST=${OPTARG};((NUMBER_OF_ARGUMENTS++));;
	  s) GENOME_SIZE=${OPTARG};((NUMBER_OF_ARGUMENTS++));;
	  t) THREADS=${OPTARG};((NUMBER_OF_ARGUMENTS++));;
	  c) CONFIG_FILENAME=${OPTARG};((NUMBER_OF_ARGUMENTS++));;
	  \?) echo -e "Invalid argument: -${OPTARG}.\n${USAGE}"; exit 1;;
	  :) echo -e "Missing argument for -${OPTARG}.\n${USAGE}"; exit 1;;
      esac
done
if [ $NUMBER_OF_ARGUMENTS -lt 5 ]; then
    echo -e "Missing command line arguments.\n${USAGE}"
    exit 3
fi
if [ $NUMBER_OF_ARGUMENTS -gt 5 ]; then
    echo -e "At least one command line argument was provided multiple times.\n${USAGE}"
    exit 3
fi

#Check if config file exists
if [ ! -f $CONFIG_FILENAME ]; then
    echo "Cannot find a config file named ${CONFIG_FILENAME}."
    exit 3
fi 

#Set name for new config file and check if file with this name already exists.
NEW_CONFIG_FILENAME="${CONFIG_FILENAME_PREFIX}${CONFIG_FILENAME}"
if [ -f $NEW_CONFIG_FILENAME ]; then
    echo "A file named ${NEW_CONFIG_FILENAME} already exists in the current working directory."
    exit 3
fi

#Write new config file with command line arguments filled in.
PROJECT_WRITTEN=0
ONT_READ_LIST_WRITTEN=0
GENOME_SIZE_WRITTEN=0
THREADS_WRITTEN=0
while read line; do
    case "$line" in
	"PROJECT=")
	    echo "PROJECT=${PROJECT_NAME}" > $NEW_CONFIG_FILENAME
	    PROJECT_WRITTEN=1;;
	"ONT_READ_LIST=")
	    echo "ONT_READ_LIST=${ONT_READ_LIST}" >> $NEW_CONFIG_FILENAME
	    ONT_READ_LIST_WRITTEN=1;;
	"GENOME_SIZE=")
	    echo "GENOME_SIZE=${GENOME_SIZE}" >> $NEW_CONFIG_FILENAME
	    GENOME_SIZE_WRITTEN=1;;
	"THREADS=4")
	    echo "THREADS=${THREADS}" >> $NEW_CONFIG_FILENAME
	    THREADS_WRITTEN=1;;
	*)
	    echo "$line" >> $NEW_CONFIG_FILENAME;;
	esac
done < <(cat $CONFIG_FILENAME)
WRITTEN_SUM=$(($PROJECT_WRITTEN+$ONT_READ_LIST_WRITTEN+$GENOME_SIZE_WRITTEN+$THREADS_WRITTEN))
if [ $WRITTEN_SUM != 4 ]; then
    echo -e "One or more of the arguments you provided could not be written to the config file. \nMaybe an update in NECAT caused this script to become incompatible. Please manually check your config file before using it."
    exit 3
fi
exit 0
